# Generated by Django 4.2.6 on 2023-11-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_cat_title_remove_product_subcat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='subcat',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='product',
            name='documentation',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка документа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat',
            field=models.ManyToManyField(blank=True, to='website.subcat', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
