# Generated by Django 4.2.6 on 2023-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_cat_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='subcat',
            field=models.ManyToManyField(blank=True, null=True, to='website.subcat', verbose_name='Subcat'),
        ),
    ]
