# Generated by Django 4.2.6 on 2023-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_cat_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='documentation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка документа'),
        ),
    ]
