# Generated by Django 5.0 on 2023-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_product_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, verbose_name='номер телефона')),
                ('message', models.TextField(verbose_name='Сообшение')),
                ('tick', models.BooleanField(default=False, verbose_name='Ответили клиенту: ')),
            ],
        ),
    ]
